// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6-nx7LIJ5Z34StIpEwoSyO-IPHnVOfWY',
    appId: '1:847494511476:web:072351b8a68baf914f8a21',
    messagingSenderId: '847494511476',
    projectId: 'gazelist-app',
    authDomain: 'gazelist-app.firebaseapp.com',
    databaseURL: 'https://gazelist-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gazelist-app.appspot.com',
    measurementId: 'G-4P4126PNHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-eRyJdtOUY1Ru-SDk53M-jeax3ymuGk',
    appId: '1:847494511476:android:0306b16029416f884f8a21',
    messagingSenderId: '847494511476',
    projectId: 'gazelist-app',
    databaseURL: 'https://gazelist-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gazelist-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLK43Vkq7A-yz_1oW-mhlHoecgaTXNFVM',
    appId: '1:847494511476:ios:1bdf566fb14a3dc84f8a21',
    messagingSenderId: '847494511476',
    projectId: 'gazelist-app',
    databaseURL: 'https://gazelist-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gazelist-app.appspot.com',
    iosClientId: '847494511476-dh3ugitmao6u3jtp19iqg0mr0apmejlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gazelist',
  );
}
